apiVersion: v1
kind: Service
metadata:
  labels:
    app: kimai
  name: kimai
spec:
  type: NodePort
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    app: kimai
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kimai-mysql
  name: kimai-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kimai
  name: kimai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kimai
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/kimai-k8s-default: "true"
        app: kimai
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: KIMAI_DATABASE
                  name: kimai-env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: KIMAI_DATABASE_PASSWORD
                  name: kimai-env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: KIMAI_DATABASE_USER
                  name: kimai-env
            - name: DATABASE_URL
              value: "mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@127.0.0.1:3306/$(MYSQL_DATABASE)?charset=utf8mb4&serverVersion=8.3.0-1.el8"
          image: kimai/kimai2:apache
          name: kimai
          ports:
            - containerPort: 8001
        - env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: KIMAI_DATABASE
                  name: kimai-env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: KIMAI_DATABASE_PASSWORD
                  name: kimai-env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: KIMAI_ROOT_PASSWORD
                  name: kimai-env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: KIMAI_DATABASE_USER
                  name: kimai-env
          image: mysql:8
          args:
            - --default-authentication-plugin=mysql_native_password
          name: kimai-mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: kimai-mysql
      restartPolicy: Always
      volumes:
        - name: kimai-mysql
          persistentVolumeClaim:
            claimName: kimai-mysql
